### ISSUE TITLE
Is there a way to run the Example_EEG_NYHead.ipynb example without using mpi?

### ISSUE THREAD

**Issue by claireshort4** [LFPy/LFPykit#139]
I am having so much trouble with open-mpi on a MacBook Air M1 chip, that it's completely stopping me from getting any work done with this. I will attach the specific issue here but since it's not the first time mpi has caused me trouble I am wondering if it would be a quick fix to run this on the cloud or just without mpi? 

Thanks
<img width="802" alt="Screen Shot 2021-08-05 at 1 15 04 PM" src="https://user-images.githubusercontent.com/28039343/128405919-25bcd364-5f85-4e18-8929-3021478cead8.png">

**Comment by espenhgn** [comment]
Hi Claire! Sorry you're having problems. This isn't really an LFPy/LFPykit issue per se, but I'll try and help anyway as I'm also using an M1 mac and have found a working solution. The basic issue is that the mpi4py Python module doesn't find the MPI dynamic libraries that it expects (it's `from mpi4py import MPI` that's failing after all). There could be many reasons for that, but I don't know exactly what in your case. The file `/Users/claire/opt/local/lib/libmpi.20.dylib` is either gone or wrong. 

So what I've done is to make sure that that everything related to Python is compiled natively for this new arm64 architecture (in contrast to the older x86_64 architecture). The latter may work via Rosetta 2 (some virtualisation thingy by Apple allowing x86_64 software to run on M1), but things cannot be mixed. So here's how I've set things up: 
- I use Miniforge from https://github.com/conda-forge/miniforge. Get the Miniforge3-MacOSX-arm64 installer, and install it. Miniforge is similar to Miniconda (a more barebones version of Anaconda Python), but prefers packages from conda-forge.org. 
- Download and install the M1/arm64 installer for NEURON from https://neuron.yale.edu/neuron/. I'm pretty sure I said "yes" to every option. However, I vaguely remember that it wrote the lines
  ```
  export PATH="/Applications/NEURON/bin":$PATH #added by NEURON installer
  export PYTHONPATH="/Applications/NEURON/lib/python":$PYTHONPATH #added by NEURON installer
  ```
  to `$HOME/.bashrc` which should rather be put in `$HOME/.zshrc` as `zsh` is now the default Terminal program, not `bash`. You may have to fix these files manually if this happens. 
- If everything went well, you now have the command `conda` in a fresh Terminal tab. In order to create a conda environment with Python, Jupyter, LFPy and its dependencies you may type in
  ```
  % conda create -n lfpy python pip mpi4py jupyter lfpykit c-compiler cxx-compiler cython matplotilb -y # create env
  % conda activate lfpy # activate env
  % pip install LFPy
  ```
- You can then test the LFPykit example notebook you had problems with, just invoke `jupyter-notebook` from the conda environment that was created.

If all fails, I've had no problems installing LFPy etc. in Google Colab notebooks for instance; just include `!pip install LFPy` at the top of each notebook. It may be an issue to download the huge NYhead model file for each session though.

**Comment by espenhgn** [comment]
Hi again. Did you figure out a fix? I'm closing this (for now) as it's not a direct issue with LFPykit I think. However, another solution would be to modify LFPy from https://github.com/LFPy/LFPy itself. 
If you won't ever need it's network functionality you could most likely comment out this line https://github.com/LFPy/LFPy/blob/6a6d7d38febbb4bf871b007e683589ba4db0168a/LFPy/__init__.py#L68 locally before reinstalling LFPy (or find the corresponding file in your local installation `... /site-packages/LFPy/__init__.py`) and avoid importing mpi4py/MPI altogether.
